// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KillRequest struct {
	RequesterId          string   `protobuf:"bytes,1,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillRequest) Reset()         { *m = KillRequest{} }
func (m *KillRequest) String() string { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()    {}
func (*KillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *KillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillRequest.Unmarshal(m, b)
}
func (m *KillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillRequest.Marshal(b, m, deterministic)
}
func (m *KillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillRequest.Merge(m, src)
}
func (m *KillRequest) XXX_Size() int {
	return xxx_messageInfo_KillRequest.Size(m)
}
func (m *KillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillRequest proto.InternalMessageInfo

func (m *KillRequest) GetRequesterId() string {
	if m != nil {
		return m.RequesterId
	}
	return ""
}

type KillResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillResponse) Reset()         { *m = KillResponse{} }
func (m *KillResponse) String() string { return proto.CompactTextString(m) }
func (*KillResponse) ProtoMessage()    {}
func (*KillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *KillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillResponse.Unmarshal(m, b)
}
func (m *KillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillResponse.Marshal(b, m, deterministic)
}
func (m *KillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillResponse.Merge(m, src)
}
func (m *KillResponse) XXX_Size() int {
	return xxx_messageInfo_KillResponse.Size(m)
}
func (m *KillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillResponse proto.InternalMessageInfo

type GetHostKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostKeyRequest) Reset()         { *m = GetHostKeyRequest{} }
func (m *GetHostKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostKeyRequest) ProtoMessage()    {}
func (*GetHostKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *GetHostKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostKeyRequest.Unmarshal(m, b)
}
func (m *GetHostKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetHostKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostKeyRequest.Merge(m, src)
}
func (m *GetHostKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostKeyRequest.Size(m)
}
func (m *GetHostKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostKeyRequest proto.InternalMessageInfo

type GetHostKeyResponse struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostKeyResponse) Reset()         { *m = GetHostKeyResponse{} }
func (m *GetHostKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetHostKeyResponse) ProtoMessage()    {}
func (*GetHostKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *GetHostKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostKeyResponse.Unmarshal(m, b)
}
func (m *GetHostKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostKeyResponse.Marshal(b, m, deterministic)
}
func (m *GetHostKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostKeyResponse.Merge(m, src)
}
func (m *GetHostKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetHostKeyResponse.Size(m)
}
func (m *GetHostKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostKeyResponse proto.InternalMessageInfo

func (m *GetHostKeyResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type PutSignedHostKeyRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutSignedHostKeyRequest) Reset()         { *m = PutSignedHostKeyRequest{} }
func (m *PutSignedHostKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PutSignedHostKeyRequest) ProtoMessage()    {}
func (*PutSignedHostKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *PutSignedHostKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSignedHostKeyRequest.Unmarshal(m, b)
}
func (m *PutSignedHostKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSignedHostKeyRequest.Marshal(b, m, deterministic)
}
func (m *PutSignedHostKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSignedHostKeyRequest.Merge(m, src)
}
func (m *PutSignedHostKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PutSignedHostKeyRequest.Size(m)
}
func (m *PutSignedHostKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSignedHostKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutSignedHostKeyRequest proto.InternalMessageInfo

func (m *PutSignedHostKeyRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type PutSignedHostKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutSignedHostKeyResponse) Reset()         { *m = PutSignedHostKeyResponse{} }
func (m *PutSignedHostKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PutSignedHostKeyResponse) ProtoMessage()    {}
func (*PutSignedHostKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *PutSignedHostKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSignedHostKeyResponse.Unmarshal(m, b)
}
func (m *PutSignedHostKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSignedHostKeyResponse.Marshal(b, m, deterministic)
}
func (m *PutSignedHostKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSignedHostKeyResponse.Merge(m, src)
}
func (m *PutSignedHostKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PutSignedHostKeyResponse.Size(m)
}
func (m *PutSignedHostKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSignedHostKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutSignedHostKeyResponse proto.InternalMessageInfo

type PutUrlRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUrlRequest) Reset()         { *m = PutUrlRequest{} }
func (m *PutUrlRequest) String() string { return proto.CompactTextString(m) }
func (*PutUrlRequest) ProtoMessage()    {}
func (*PutUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *PutUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUrlRequest.Unmarshal(m, b)
}
func (m *PutUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUrlRequest.Marshal(b, m, deterministic)
}
func (m *PutUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUrlRequest.Merge(m, src)
}
func (m *PutUrlRequest) XXX_Size() int {
	return xxx_messageInfo_PutUrlRequest.Size(m)
}
func (m *PutUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUrlRequest proto.InternalMessageInfo

func (m *PutUrlRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type PutUrlResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUrlResponse) Reset()         { *m = PutUrlResponse{} }
func (m *PutUrlResponse) String() string { return proto.CompactTextString(m) }
func (*PutUrlResponse) ProtoMessage()    {}
func (*PutUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{7}
}

func (m *PutUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUrlResponse.Unmarshal(m, b)
}
func (m *PutUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUrlResponse.Marshal(b, m, deterministic)
}
func (m *PutUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUrlResponse.Merge(m, src)
}
func (m *PutUrlResponse) XXX_Size() int {
	return xxx_messageInfo_PutUrlResponse.Size(m)
}
func (m *PutUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutUrlResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*KillRequest)(nil), "pb.KillRequest")
	proto.RegisterType((*KillResponse)(nil), "pb.KillResponse")
	proto.RegisterType((*GetHostKeyRequest)(nil), "pb.GetHostKeyRequest")
	proto.RegisterType((*GetHostKeyResponse)(nil), "pb.GetHostKeyResponse")
	proto.RegisterType((*PutSignedHostKeyRequest)(nil), "pb.PutSignedHostKeyRequest")
	proto.RegisterType((*PutSignedHostKeyResponse)(nil), "pb.PutSignedHostKeyResponse")
	proto.RegisterType((*PutUrlRequest)(nil), "pb.PutUrlRequest")
	proto.RegisterType((*PutUrlResponse)(nil), "pb.PutUrlResponse")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x75, 0x53, 0x06, 0x7e, 0x9b, 0x5d, 0xf7, 0x89, 0x3a, 0xa2, 0x87, 0x99, 0x83, 0x08, 0x83,
	0x8a, 0x7a, 0xf6, 0xe4, 0x41, 0x65, 0x82, 0xa3, 0xe2, 0x1f, 0xa8, 0xfb, 0x90, 0x62, 0x68, 0x6a,
	0x92, 0x1e, 0x76, 0xf4, 0x9f, 0x4b, 0x9a, 0x6c, 0x8d, 0x5b, 0x77, 0x7b, 0xbc, 0xbc, 0xf7, 0x92,
	0xf7, 0x08, 0x44, 0xa5, 0x92, 0x46, 0x7e, 0x4a, 0x91, 0xd4, 0x00, 0xbb, 0x65, 0xc6, 0x6f, 0xa0,
	0x3f, 0xcb, 0x85, 0x48, 0xe9, 0xa7, 0x22, 0x6d, 0x70, 0x02, 0x7d, 0xe5, 0x20, 0xa9, 0x97, 0xc5,
	0xb8, 0x33, 0xe9, 0x5c, 0x1f, 0xa6, 0x21, 0xc5, 0x23, 0x18, 0x38, 0x83, 0x2e, 0x65, 0xa1, 0x89,
	0x1f, 0xc3, 0xe8, 0x89, 0xcc, 0xb3, 0xd4, 0x66, 0x46, 0x4b, 0x1f, 0xc3, 0xaf, 0x00, 0x43, 0xd2,
	0x49, 0x31, 0x86, 0xfd, 0x6f, 0x5a, 0xd6, 0xa1, 0x83, 0xd4, 0x42, 0x3e, 0x85, 0xb3, 0x79, 0x65,
	0xde, 0xf3, 0xaf, 0x82, 0x16, 0xff, 0x23, 0x5a, 0xc4, 0x0c, 0xc6, 0xdb, 0x62, 0xff, 0x8a, 0x4b,
	0x38, 0x9a, 0x57, 0xe6, 0x43, 0x89, 0xc0, 0x5e, 0x29, 0xe1, 0x0b, 0x58, 0xc8, 0x63, 0x88, 0x56,
	0x12, 0x67, 0xba, 0xfb, 0xed, 0xc2, 0xf0, 0x35, 0xd7, 0x86, 0x0a, 0x52, 0x8f, 0xb2, 0x30, 0x4a,
	0x0a, 0x9c, 0xc2, 0x81, 0xad, 0x87, 0xc3, 0xa4, 0xcc, 0x92, 0x60, 0x19, 0x16, 0x37, 0x84, 0xbf,
	0x73, 0x0f, 0x1f, 0x00, 0x9a, 0x9a, 0x78, 0x62, 0x15, 0x5b, 0x5b, 0xb0, 0xd3, 0x4d, 0x7a, 0x6d,
	0x7f, 0x83, 0x78, 0xb3, 0x10, 0x9e, 0x5b, 0xf5, 0x8e, 0x4d, 0xd8, 0x45, 0xfb, 0xe1, 0x3a, 0xf0,
	0x16, 0x7a, 0xae, 0x22, 0x8e, 0xbc, 0xb2, 0x59, 0x84, 0x61, 0x48, 0xad, 0x2c, 0x59, 0xaf, 0xfe,
	0x0a, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x0b, 0x83, 0x8d, 0x1c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ListenerControlClient is the client API for ListenerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListenerControlClient interface {
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	GetHostKey(ctx context.Context, in *GetHostKeyRequest, opts ...grpc.CallOption) (*GetHostKeyResponse, error)
	PutSignedHostKey(ctx context.Context, in *PutSignedHostKeyRequest, opts ...grpc.CallOption) (*PutSignedHostKeyResponse, error)
	PutUrl(ctx context.Context, in *PutUrlRequest, opts ...grpc.CallOption) (*PutUrlResponse, error)
}

type listenerControlClient struct {
	cc *grpc.ClientConn
}

func NewListenerControlClient(cc *grpc.ClientConn) ListenerControlClient {
	return &listenerControlClient{cc}
}

func (c *listenerControlClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, "/pb.ListenerControl/Kill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerControlClient) GetHostKey(ctx context.Context, in *GetHostKeyRequest, opts ...grpc.CallOption) (*GetHostKeyResponse, error) {
	out := new(GetHostKeyResponse)
	err := c.cc.Invoke(ctx, "/pb.ListenerControl/GetHostKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerControlClient) PutSignedHostKey(ctx context.Context, in *PutSignedHostKeyRequest, opts ...grpc.CallOption) (*PutSignedHostKeyResponse, error) {
	out := new(PutSignedHostKeyResponse)
	err := c.cc.Invoke(ctx, "/pb.ListenerControl/PutSignedHostKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerControlClient) PutUrl(ctx context.Context, in *PutUrlRequest, opts ...grpc.CallOption) (*PutUrlResponse, error) {
	out := new(PutUrlResponse)
	err := c.cc.Invoke(ctx, "/pb.ListenerControl/PutUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListenerControlServer is the server API for ListenerControl service.
type ListenerControlServer interface {
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	GetHostKey(context.Context, *GetHostKeyRequest) (*GetHostKeyResponse, error)
	PutSignedHostKey(context.Context, *PutSignedHostKeyRequest) (*PutSignedHostKeyResponse, error)
	PutUrl(context.Context, *PutUrlRequest) (*PutUrlResponse, error)
}

// UnimplementedListenerControlServer can be embedded to have forward compatible implementations.
type UnimplementedListenerControlServer struct {
}

func (*UnimplementedListenerControlServer) Kill(ctx context.Context, req *KillRequest) (*KillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kill not implemented")
}
func (*UnimplementedListenerControlServer) GetHostKey(ctx context.Context, req *GetHostKeyRequest) (*GetHostKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostKey not implemented")
}
func (*UnimplementedListenerControlServer) PutSignedHostKey(ctx context.Context, req *PutSignedHostKeyRequest) (*PutSignedHostKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutSignedHostKey not implemented")
}
func (*UnimplementedListenerControlServer) PutUrl(ctx context.Context, req *PutUrlRequest) (*PutUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUrl not implemented")
}

func RegisterListenerControlServer(s *grpc.Server, srv ListenerControlServer) {
	s.RegisterService(&_ListenerControl_serviceDesc, srv)
}

func _ListenerControl_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerControlServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ListenerControl/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerControlServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerControl_GetHostKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerControlServer).GetHostKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ListenerControl/GetHostKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerControlServer).GetHostKey(ctx, req.(*GetHostKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerControl_PutSignedHostKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSignedHostKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerControlServer).PutSignedHostKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ListenerControl/PutSignedHostKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerControlServer).PutSignedHostKey(ctx, req.(*PutSignedHostKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerControl_PutUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerControlServer).PutUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ListenerControl/PutUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerControlServer).PutUrl(ctx, req.(*PutUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListenerControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ListenerControl",
	HandlerType: (*ListenerControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kill",
			Handler:    _ListenerControl_Kill_Handler,
		},
		{
			MethodName: "GetHostKey",
			Handler:    _ListenerControl_GetHostKey_Handler,
		},
		{
			MethodName: "PutSignedHostKey",
			Handler:    _ListenerControl_PutSignedHostKey_Handler,
		},
		{
			MethodName: "PutUrl",
			Handler:    _ListenerControl_PutUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}
